### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by cameronelliott** [victorsteven/jwt-best-practices#2]
I really liked your article, and this code,but for me to use it at my company, I really need an MIT license or similar.
Please consider adding an MIT license.
Thanks for publishing the article.

**Comment by victorsteven** [comment]
License added to the complete code and also this one. Thanks a lot @cameronelliott

**Comment by cameronelliott** [comment]
@victorsteven Thanks for publishing this code, it is great article, and helpful repo  :100:
