### ISSUE TITLE
Missing code?

### ISSUE THREAD

**Issue by cameronelliott** [victorsteven/jwt-best-practices#3]
Reviewing the code and the article, it seems the commited code is missing some pieces that are shown in the article:

- TokenValid() is defined but not called/referenced
- TokenAuthMiddleware() is not defined or used in the repo, but is used in the article.

Maybe you want to add the code in the article to the repo?

**Comment by victorsteven** [comment]
Sure, I will add them. 
Thanks for this.

**Comment by victorsteven** [comment]
Okay, I have added link to the README.md file that has the complete code, with the middlewares, you can also get them [here](https://github.com/victorsteven/gophercon-jwt-repo). 
If you have any questions, I will be glad to answer. Thanks.

**Comment by cameronelliott** [comment]
Thank you very much!!

**Comment by cameronelliott** [comment]
@victorsteven You really should consider adding a license if you want other people to consider using this code.
Please see my other issue filed, "LiCENSE"

**Comment by victorsteven** [comment]
License added to the complete code. Thanks a lot @cameronelliott
